application: auction-items
version: 1
runtime: python27
threadsafe: true
api_version: 1

libraries:
- name: lxml
  version: latest
- name: jinja2
  version: latest
- name: pycrypto
  version: latest

builtins:
- deferred: on

# builtins:
 # - appstats: on

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^db_backup/*
- ^result*
- ^client/dist/bower_components/*
- ^client/node_modules/*
- ^client/app/.*  # comment it for LOCAL DEVELOPMENT STATIC

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

# PRODUCTION STATIC
- url: /styles
  static_dir: client/dist/styles

- url: /views
  static_dir: client/dist/views

- url: /bower_components
  static_dir: client/dist/bower_components

- url: /scripts
  static_dir: client/dist/scripts

- url: /images
  static_dir: client/dist/images

# LOCAL DEVELOPMENT STATIC
#- url: /styles
#  static_dir: client/app/styles
#
#- url: /views
#  static_dir: client/app/views
#
#- url: /bower_components
#  static_dir: client/app/bower_components
#
#- url: /scripts
#  static_dir: client/app/scripts
#
#- url: /images
#  static_dir: client/app/images
#
# OLD NON-YEOMAN FRONTEND
#- url: /css
#  static_dir: css
#
#- url: /scripts
#  static_dir: scripts
#
#- url: /images
#  static_dir: images
#
#- url: /bootstrap
#  static_dir: bootstrap
#
#- url: /themes
#  static_dir: themes
#
#- url: /partials
#  static_dir: templates/partials

# HANDLERS
- url: /
  script: apphandlers.app

- url: /PersonActions
  script: apphandlers.app

- url: /update
  script: apphandlers.app
  login: admin

- url: /createfilters
  script: apphandlers.app
  login: admin

- url: /cleardb
  script: apphandlers.app
  login: admin

